# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitsweeper" do
  desc "A command-line tool for cleaning up merged Git branches"
  homepage "https://github.com/petems/gitsweeper"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitsweeper"

  on_macos do
    on_intel do
      url "https://github.com/petems/gitsweeper/releases/download/v0.1.0/gitsweeper-0.1.0-darwin-amd64.tar.gz"
      sha256 "aeb860a60aaaae12ed1c19f8e87c536a0199182dc71eca2ad3804f28384a79ff"
    end
    on_arm do
      url "https://github.com/petems/gitsweeper/releases/download/v0.1.0/gitsweeper-0.1.0-darwin-arm64.tar.gz"
      sha256 "28107848cf2f725b7e1f520cb4a4619664f4eb4b447d6352e434743696592c24"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/petems/gitsweeper/releases/download/v0.1.0/gitsweeper-0.1.0-linux-amd64.tar.gz"
      sha256 "13e8b3f03701a24a6db439344d9bc1b9a13196046d3acefd3fabcc2125326161"
    end
    on_arm do
      url "https://github.com/petems/gitsweeper/releases/download/v0.1.0/gitsweeper-0.1.0-linux-arm64.tar.gz"
      sha256 "f8b8f9dce7be5465f38150990b638056dca679e0f023cd9a2201be33d81c99e0"
    end
  end

  caveats do
    "gitsweeper is a tool for cleaning up merged Git branches."
    ""
    "To get started:"
    "  gitsweeper --help"
  end

  # No zap stanza required
end
