# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitsweeper" do
  desc "A command-line tool for cleaning up merged Git branches"
  homepage "https://github.com/petems/gitsweeper"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitsweeper"

  on_macos do
    on_intel do
      url "https://github.com/petems/gitsweeper/releases/download/v0.1.0/gitsweeper-0.1.0-darwin-amd64.tar.gz"
      sha256 "ae0316e0b4163d905e3cc647c92d3a22b93e63ee6901ea4f2b7a23d2ac89fa75"
    end
    on_arm do
      url "https://github.com/petems/gitsweeper/releases/download/v0.1.0/gitsweeper-0.1.0-darwin-arm64.tar.gz"
      sha256 "980ebc9554c171a516c99677f953777d96626bee40bf15273e0b2cfd98559caf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/petems/gitsweeper/releases/download/v0.1.0/gitsweeper-0.1.0-linux-amd64.tar.gz"
      sha256 "05ea978aceaa20cd3c06e2fba52537002336659ffd0fe2d38535516d31afef45"
    end
    on_arm do
      url "https://github.com/petems/gitsweeper/releases/download/v0.1.0/gitsweeper-0.1.0-linux-arm64.tar.gz"
      sha256 "f30e7dd27fee446142fdbba365cdf623e17718f16dfb742f49329292346a9cb5"
    end
  end

  caveats do
    "gitsweeper is a tool for cleaning up merged Git branches."
    ""
    "To get started:"
    "  gitsweeper --help"
  end

  # No zap stanza required
end
