# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitsweeper" do
  desc "A command-line tool for cleaning up merged Git branches"
  homepage "https://github.com/petems/gitsweeper"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitsweeper"

  on_macos do
    on_intel do
      url "https://github.com/petems/gitsweeper/releases/download/v0.1.0/gitsweeper-0.1.0-darwin-amd64.tar.gz"
      sha256 "4eea931becefb42e82d30a94017309dd81ea8049844040399766dcfd81fb738c"
    end
    on_arm do
      url "https://github.com/petems/gitsweeper/releases/download/v0.1.0/gitsweeper-0.1.0-darwin-arm64.tar.gz"
      sha256 "882ff01fa2c8ce3fb7d64e73db64bdb23985e23c3a82bf1ad954060b8884577c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/petems/gitsweeper/releases/download/v0.1.0/gitsweeper-0.1.0-linux-amd64.tar.gz"
      sha256 "ce9e0d6dbfcf733851ef003c89681f3f4f996c773e38ed1574602cb5f2ba3e1e"
    end
    on_arm do
      url "https://github.com/petems/gitsweeper/releases/download/v0.1.0/gitsweeper-0.1.0-linux-arm64.tar.gz"
      sha256 "e1b384a8f151c6995f1c028e3568522e52bdcba7cfb3eb871b34cd8e3e422c3b"
    end
  end

  caveats do
    "gitsweeper is a tool for cleaning up merged Git branches."
    ""
    "To get started:"
    "  gitsweeper --help"
  end

  # No zap stanza required
end
