name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Run weekly to check for updates
    - cron: '0 0 * * 0'

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        ruby-version: ['3.3']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Tap this repository
      run: |
        brew tap petems/homebrew-gitsweeper $GITHUB_WORKSPACE

    - name: Test cask syntax
      run: |
        brew audit --strict --online --cask gitsweeper

    - name: Test cask installation (dry-run)
      run: |
        brew install --dry-run --cask gitsweeper

    - name: Test cask with brew style
      run: |
        brew style --cask gitsweeper

  update-check:
    runs-on: macos-latest
    if: github.event_name == 'schedule'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - name: Tap this repository
      run: |
        brew tap petems/homebrew-gitsweeper $GITHUB_WORKSPACE

    - name: Check for updates
      run: |
        brew livecheck --cask gitsweeper

  security:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run CodeQL Analysis
      uses: github/codeql-action/init@v3
      with:
        languages: ruby

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3 