name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Run weekly to check for updates
    - cron: '0 0 * * 0'

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        ruby-version: ['3.3']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Test formula syntax
      run: |
        brew audit --strict --online Casks/gitsweeper.rb

    - name: Test formula installation (dry-run)
      run: |
        brew install --dry-run Casks/gitsweeper.rb

    - name: Test formula with brew style
      run: |
        brew style Casks/gitsweeper.rb

  update-check:
    runs-on: macos-latest
    if: github.event_name == 'schedule'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Check for updates
      run: |
        brew livecheck Casks/gitsweeper.rb

  security:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run CodeQL Analysis
      uses: github/codeql-action/init@v3
      with:
        languages: ruby

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3 