name: Validate Formula Update

on:
  push:
    paths:
      - 'Casks/gitsweeper.rb'
    branches: [ master ]

jobs:
  validate:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Validate formula syntax
      run: |
        brew audit --strict --online Casks/gitsweeper.rb

    - name: Check formula style
      run: |
        brew style Casks/gitsweeper.rb

    - name: Test formula installation (dry-run)
      run: |
        brew install --dry-run Casks/gitsweeper.rb

    - name: Verify download URLs
      run: |
        # Extract URLs from the formula and verify they're accessible
        grep -o 'https://github.com/petems/gitsweeper/releases/download/[^"]*' Casks/gitsweeper.rb | while read -r url; do
          echo "Checking URL: $url"
          curl -I "$url" | head -1
        done

    - name: Verify SHA256 checksums
      run: |
        # Extract URLs and SHA256s, then verify
        grep -A 1 'url "https://github.com/petems/gitsweeper/releases/download/' Casks/gitsweeper.rb | while read -r url_line && read -r sha_line; do
          url="${url_line#*url \"}"
          url="${url%\"*}"
          expected_sha="${sha_line#*sha256 \"}"
          expected_sha="${expected_sha%\"*}"
          
          echo "Verifying: $url"
          actual_sha=$(curl -sL "$url" | shasum -a 256 | cut -d' ' -f1)
          
          if [ "$expected_sha" = "$actual_sha" ]; then
            echo "✅ SHA256 matches for $url"
          else
            echo "❌ SHA256 mismatch for $url"
            echo "Expected: $expected_sha"
            echo "Actual:   $actual_sha"
            exit 1
          fi
        done

    - name: Create validation report
      if: always()
      run: |
        {
          echo "## Formula Validation Report"
          echo ""
          echo "✅ Formula syntax validation passed"
          echo "✅ Formula style check passed"
          echo "✅ Installation dry-run passed"
          echo "✅ Download URLs are accessible"
          echo "✅ SHA256 checksums verified"
          echo ""
          echo "Formula is ready for distribution!"
        } >> "$GITHUB_STEP_SUMMARY" 